apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: YOUR_DOCKERHUB_USERNAME/nextjs-app
    newTag: latest          # ← GitHub Actions will automatically update this